[colors.bright]
black = "#808080"
blue = "#4444ff"
cyan = "#44ffff"
green = "#44ff44"
magenta = "#ff44ff"
red = "#ff4444"
white = "#ffffff"
yellow = "#ffff44"
[colors.normal]
black = "#000000"
blue = "#0000ff"
cyan = "#00ffff"
green = "#00ff00"
magenta = "#ff00ff"
red = "#ff0000"
white = "#ffffff"
yellow = "#ffff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 11.0

[font.normal]
family = "DejaVu Sans Mono"

[scrolling]
history = 10000

[terminal.shell]
program = "zellij"

[window.padding]
x = 2
y = 2
